### ISSUE TITLE
COSP phase needs unit test

### ISSUE THREAD

**Issue by rcjackson** [columncolab/EMC2#36]
The COSP phase simulator needs a unit test, but right now I am currently thinking about how to write it. It seems to depend on a sigma_180 variable which isn't generated by the subcolumn generator.

**Comment by isilber** [comment]
sigma_180 is calculated under the 'calc_theory_beta_m' method (calculation of molecular backscatter) and has a minor impact on the resultant backscatter when hydrometers exist. Not sure whether this helps.

**Comment by rcjackson** [comment]
This is now fixed. Closing.
