### ISSUE TITLE
Travis-CI stopped building and testing commits

### ISSUE THREAD

**Issue by isilber** [columncolab/EMC2#66]

**Comment by isilber** [comment]
Going through their updated documentation, it appears that we need to request a special OSS credit for our builds, which I presume we will likely be granted.
See: https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by rcjackson** [comment]
I'm going to switch to GitHub Actions, which does the same testing without the costs. It's also much easier to implement than Travis CI. I've already started to use it for some of my other projects.

**Comment by rcjackson** [comment]
I've went ahead and switched CI to GitHub Actions. This issue is now solved.
