### ISSUE TITLE
EMC2 documentation is outdated.

### ISSUE THREAD

**Issue by isilber** [columncolab/EMC2#86]
The documentation API requires a significant update

**Comment by rcjackson** [comment]
I found an issue in the GitHub Action that was causing the page to build but not deploy to gh-pages. Essentially, it was set to only run on a branch that doesn't exist in our repo. I went through and fixed the offending issue and the page looks more up to date. Go ahead and have a check and if it looks good please feel free to close.

**Comment by isilber** [comment]
Yes, I see the impact of 'main' vs. 'master' branch names. The documentation looks good now. I also updated its example notebook (with a simple rerun as it was outdated as well).
This issue is now resolved.
